export {
  CertifiedZeroOverlayProvider,
  OverlayCutoverError,
  catchUpOverlay,
  zeroOverlayProviderId,
  zeroOverlayProviderVersion,
  type OverlayCatchUpInput,
  type OverlayCatchUpResult,
  type OverlayDelta,
  type OverlayDeltaReader,
  type OverlayErrorCode,
  type OverlayHead,
  type OverlayInventoryEvidence,
  type OverlayInventoryPort,
  type OverlayProvider,
} from "@ontos/materialization-application";
