export { QueryDomainError, type QueryDomainErrorCode } from "./error.ts";
export {
  compileLinkCandidate,
  compileObjectCount,
  compileObjectGet,
  compileObjectSearch,
  type ObjectGetCompileRequest,
  type QueryCompilerContext,
  type QueryTextDigester,
} from "./compiler.ts";
export {
  QUERY_COMPILER_VERSION,
  QUERY_COMPLEXITY_MAXIMUM_UNITS,
  QUERY_RESULT_DEFAULT_MAXIMUM_BYTES,
  QUERY_SQL_MAXIMUM_BYTES,
  QUERY_SQL_MAXIMUM_PARAMETERS,
  QUERY_STATEMENT_DEFAULT_TIMEOUT_MS,
  QUERY_STATEMENT_MAXIMUM_TIMEOUT_MS,
  assertAuthenticQueryLogicalPlan,
  type LinkCandidateLogicalPlan,
  type ObjectCountLogicalPlan,
  type ObjectGetLogicalPlan,
  type ObjectSearchLogicalPlan,
  type QueryCanonicalParameter,
  type QueryCanonicalScalar,
  type QueryComplexityReport,
  type QueryLinkExistsPredicatePlan,
  type QueryLogicalPlan,
  type QueryOperandValueType,
  type QueryOperation,
  type QueryParameterOperand,
  type QueryPlanBinding,
  type QueryPolicyPlan,
  type QueryPredicatePlan,
  type QueryPropertyAccessPlan,
  type QueryPropertyMaskPlan,
  type QuerySearchPlan,
  type QuerySortPlan,
  type QueryTypedOperand,
} from "./model.ts";
export {
  compileLinkPolicyPlan,
  compileObjectPolicyPlan,
  propertyValueAllowedPredicate,
  requirePropertyAccess,
  requirePropertyReadAccess,
  type QueryPolicyActorAttribute,
  type QueryPolicyContext,
} from "./policy-plan.ts";
export {
  QuerySchemaRegistry,
  requireQueryProperty,
  type QueryLinkTypeSchema,
  type QueryLinkTypeSnapshot,
  type QueryObjectTypeSchema,
  type QueryObjectTypeSnapshot,
  type QueryPropertySchema,
  type QuerySchemaRegistryInput,
} from "./schema-registry.ts";
export {
  canonicalizeActorParameter,
  canonicalizeClientCollectionParameter,
  canonicalizeClientParameter,
  canonicalizePrimaryKeyInput,
  canonicalizeRequestTimeParameter,
  canonicalizeStringArrayParameter,
  canonicalizeTrustedPolicyParameter,
  canonicalizeTrustedPolicyCollectionParameter,
  queryOperandValueType,
} from "./value.ts";
